import { serviceBase } from "./serviceRoutes";
import { text, type DetailRoute } from "./routeTypes";

export const articleRoutes: DetailRoute[] = [
  {
    kind: "article",
    path: "/blog/why-landing-pages-fail",
    slug: "why-landing-pages-fail",
    title: text(
      "Why landing pages fail before users scroll | LORA",
      "Почему лендинги проигрывают до первого скролла | LORA",
      "Por que las landing pages fallan antes del scroll | LORA",
      "为什么落地页在用户滚动前就失败 | LORA",
    ),
    description: text(
      "A practical note about first-screen conversion, offer clarity and CTA structure.",
      "Практическая заметка о первом экране, ясности оффера и структуре CTA.",
      "Nota practica sobre conversion en primera pantalla, claridad de oferta y estructura CTA.",
      "关于首屏转化、报价清晰度和 CTA 结构的实用笔记。",
    ),
    h1: text(
      "Why landing pages fail before users scroll",
      "Почему лендинги проигрывают до первого скролла",
      "Por que las landing pages fallan antes del scroll",
      "为什么落地页在用户滚动前就失败",
    ),
    summary: text(
      "The first screen has to explain value, audience and next step quickly.",
      "Первый экран должен быстро объяснить ценность, аудиторию и следующий шаг.",
      "La primera pantalla debe explicar rapido valor, audiencia y siguiente paso.",
      "首屏必须快速解释价值、受众和下一步。",
    ),
    eyebrow: text("Article", "Статья", "Articulo", "文章"),
    changeFrequency: "yearly",
    priority: 0.55,
    date: "2026-04-10",
    related: ["landing-pages", "ux-ui-design", "seo-optimization"],
    cta: text(
      "Request a landing page audit",
      "Запросить аудит лендинга",
      "Solicitar auditoria de landing",
      "请求落地页审计",
    ),
    problems: serviceBase.problems,
    deliverables: serviceBase.deliverables,
    integrations: serviceBase.integrations,
    process: serviceBase.process,
    faq: serviceBase.faq,
  },
  {
    kind: "article",
    path: "/blog/crm-that-actually-works",
    slug: "crm-that-actually-works",
    title: text(
      "CRM that actually works | LORA",
      "CRM, которая реально работает | LORA",
      "CRM que realmente funciona | LORA",
      "真正有效的 CRM | LORA",
    ),
    description: text(
      "A practical note about CRM logic, lead routing, automation and readable sales pipelines.",
      "Практическая заметка о CRM-логике, маршруте заявок, автоматизации и читаемой воронке продаж.",
      "Nota practica sobre logica CRM, rutas de leads y automatizacion.",
      "关于 CRM 逻辑、线索路由、自动化和可读销售漏斗的实用文章。",
    ),
    h1: text(
      "CRM that actually works",
      "CRM, которая реально работает",
      "CRM que realmente funciona",
      "真正有效的 CRM",
    ),
    summary: text(
      "A CRM should not just store leads. It should move them through the next action.",
      "CRM должна не просто хранить заявки. Она должна двигать их к следующему действию.",
      "Un CRM no solo guarda leads: los mueve al siguiente paso.",
      "CRM 不应只是存储线索，而应推动下一步行动。",
    ),
    eyebrow: text("Article", "Статья", "Articulo", "文章"),
    changeFrequency: "yearly",
    priority: 0.55,
    date: "2026-04-18",
    related: ["crm-integration", "websites", "ux-ui-design"],
    cta: text("Request a CRM audit", "Запросить аудит CRM", "Solicitar auditoria CRM", "请求 CRM 审计"),
    problems: serviceBase.problems,
    deliverables: serviceBase.deliverables,
    integrations: serviceBase.integrations,
    process: serviceBase.process,
    faq: serviceBase.faq,
  },
  {
    kind: "article",
    path: "/blog/revenue-machine-blueprint",
    slug: "revenue-machine-blueprint",
    title: text(
      "Revenue machine blueprint | LORA",
      "Чертеж машины выручки | LORA",
      "Blueprint de maquina de ingresos | LORA",
      "营收机器蓝图 | LORA",
    ),
    description: text(
      "A practical note about connecting traffic, pages, CRM, analytics and repeatable revenue architecture.",
      "Практическая заметка о связке трафика, страниц, CRM, аналитики и повторяемой архитектуры выручки.",
      "Nota practica sobre trafico, paginas, CRM y arquitectura de ingresos.",
      "关于连接流量、页面、CRM、分析和可重复营收架构的实用文章。",
    ),
    h1: text(
      "The revenue machine blueprint",
      "Чертеж машины выручки",
      "El blueprint de la maquina de ingresos",
      "营收机器蓝图",
    ),
    summary: text(
      "Traffic becomes predictable only when the page, CRM and follow-up work as one system.",
      "Трафик становится предсказуемым только когда страница, CRM и догрев работают как одна система.",
      "El trafico se vuelve predecible cuando pagina, CRM y seguimiento trabajan juntos.",
      "只有页面、CRM 和跟进作为一个系统运行时，流量才可预测。",
    ),
    eyebrow: text("Article", "Статья", "Articulo", "文章"),
    changeFrequency: "yearly",
    priority: 0.55,
    date: "2026-04-24",
    related: ["websites", "crm-integration", "seo-optimization"],
    cta: text(
      "Request a growth audit",
      "Запросить аудит системы роста",
      "Solicitar auditoria de crecimiento",
      "请求增长审计",
    ),
    problems: serviceBase.problems,
    deliverables: serviceBase.deliverables,
    integrations: serviceBase.integrations,
    process: serviceBase.process,
    faq: serviceBase.faq,
  },
];
