import { text, type SeoRoute } from "./routeTypes";

const agency = {
  en: "LORA builds websites, digital products, CRM integrations and conversion systems for growing companies.",
  es: "LORA crea sitios web, productos digitales, integraciones CRM y sistemas de conversion para empresas en crecimiento.",
  ru: "LORA проектирует сайты, цифровые продукты, CRM-интеграции и системы конверсии для компаний, которым нужен управляемый рост.",
  zh: "LORA 为成长型公司构建网站、数字产品、CRM 集成和转化系统。",
};

export const mainRoutes: SeoRoute[] = [
  {
    kind: "home",
    path: "/",
    slug: "home",
    title: text(
      "LORA | Revenue engineering agency",
      "LORA | Агентство системного роста",
      "LORA | Agencia de revenue engineering",
      "LORA | 收入工程 агентство",
    ),
    description: agency,
    h1: text(
      "Revenue engineering agency",
      "Агентство системного роста",
      "Agencia de revenue engineering",
      "收入工程 агентство",
    ),
    summary: agency,
    changeFrequency: "weekly",
    priority: 1,
  },
  {
    kind: "listing",
    path: "/services",
    slug: "services",
    title: text("Services | LORA", "Услуги | LORA", "Servicios | LORA", "服务 | LORA"),
    description: text(
      "Website, UX/UI, SEO, CRM and automation services by LORA.",
      "Услуги LORA: сайты, UX/UI, SEO, CRM, автоматизация и поддержка.",
      "Servicios de sitios web, UX/UI, SEO, CRM y automatizacion de LORA.",
      "LORA 网站、UX/UI、SEO、CRM 和自动化服务。",
    ),
    h1: text("Services", "Услуги", "Servicios", "服务"),
    summary: text(
      "Commercial pages for core LORA services with clear scope, process and CTA.",
      "Коммерческие страницы ключевых услуг LORA с понятным составом работ, процессом и CTA.",
      "Paginas comerciales de servicios clave de LORA.",
      "LORA 主要服务页面。",
    ),
    changeFrequency: "weekly",
    priority: 0.9,
  },
  {
    kind: "listing",
    path: "/industries",
    slug: "industries",
    title: text(
      "Industry website solutions | LORA",
      "Сайты для ниш и отраслей | LORA",
      "Soluciones por industria | LORA",
      "行业网站解决方案 | LORA",
    ),
    description: text(
      "Landing pages for restaurants, clinics, beauty, B2B, real estate and other industries.",
      "Посадочные страницы под салоны, рестораны, клиники, B2B, недвижимость и другие ниши.",
      "Paginas para restaurantes, clinicas, belleza, B2B e inmobiliaria.",
      "餐厅、诊所、美业、B2B、房地产等行业页面。",
    ),
    h1: text("Industry solutions", "Решения для ниш", "Soluciones por industria", "行业解决方案"),
    summary: text(
      "Neutral, useful industry pages prepared for SEO and future ad campaigns.",
      "Нейтральные полезные страницы ниш, подготовленные для SEO и будущей рекламы.",
      "Paginas por industria preparadas para SEO y publicidad.",
      "为 SEO 和广告准备的行业页面。",
    ),
    changeFrequency: "monthly",
    priority: 0.85,
  },
  {
    kind: "listing",
    path: "/blog",
    slug: "blog",
    title: text("Blog | LORA", "Блог | LORA", "Blog | LORA", "博客 | LORA"),
    description: text(
      "Notes about conversion, CRM, website systems and revenue architecture.",
      "Материалы о конверсии, CRM, сайтах и архитектуре роста.",
      "Notas sobre conversion, CRM, sitios web y arquitectura de ingresos.",
      "关于转化、CRM、网站系统和增长架构的文章。",
    ),
    h1: text("Blog", "Блог", "Blog", "博客"),
    summary: text(
      "Articles that connect strategy, product and implementation.",
      "Статьи на стыке стратегии, продукта и реализации.",
      "Articulos sobre estrategia, producto e implementacion.",
      "连接战略、产品与执行的文章。",
    ),
    changeFrequency: "weekly",
    priority: 0.7,
  },
  {
    kind: "simple",
    path: "/pricing",
    slug: "pricing",
    title: text("Pricing | LORA", "Цены | LORA", "Precios | LORA", "价格 | LORA"),
    description: text(
      "Starting points and project formats for websites, apps, CRM and automation.",
      "Ориентиры по стоимости сайтов, приложений, CRM и автоматизации.",
      "Rangos de precio para sitios, apps, CRM y automatizacion.",
      "网站、应用、CRM 和自动化项目价格参考。",
    ),
    h1: text("Pricing", "Цены", "Precios", "价格"),
    summary: text(
      "Use pricing as a starting point, then request a brief for a scoped estimate.",
      "Цены — ориентир. Точная оценка появляется после брифа и разбора задачи.",
      "Los precios son una referencia inicial.",
      "价格为初步参考。",
    ),
    changeFrequency: "monthly",
    priority: 0.75,
  },
  {
    kind: "simple",
    path: "/cases",
    slug: "cases",
    title: text("Cases | LORA", "Кейсы | LORA", "Casos | LORA", "案例 | LORA"),
    description: text(
      "A structured place for future verified LORA case studies.",
      "Раздел для будущих подтвержденных кейсов LORA без выдуманных результатов.",
      "Seccion para futuros casos verificados de LORA.",
      "用于未来已验证案例的页面。",
    ),
    h1: text("Cases", "Кейсы", "Casos", "案例"),
    summary: text(
      "We do not publish fake cases. This page is ready for verified work descriptions.",
      "Мы не публикуем фейковые кейсы. Страница подготовлена под реальные подтвержденные проекты.",
      "No publicamos casos inventados.",
      "不发布虚假案例。",
    ),
    changeFrequency: "monthly",
    priority: 0.55,
  },
  {
    kind: "simple",
    path: "/history",
    slug: "history",
    title: text("History | LORA", "История | LORA", "Historia | LORA", "故事 | LORA"),
    description: text(
      "The story of the LORA team, brand name and system agency formation.",
      "История команды LORA, названия бренда и формирования системного агентства.",
      "La historia del equipo LORA, el nombre y la agencia.",
      "LORA 团队、品牌名称和系统机构形成的故事。",
    ),
    h1: text("History", "История", "Historia", "故事"),
    summary: text(
      "How LORA formed as a team and became a system agency.",
      "Как LORA собралась в команду и стала системным агентством.",
      "Como LORA se formo como equipo.",
      "LORA 如何成为一个团队。",
    ),
    changeFrequency: "monthly",
    priority: 0.55,
  },
  {
    kind: "simple",
    path: "/contacts",
    slug: "contacts",
    title: text("Contacts | LORA", "Контакты | LORA", "Contacto | LORA", "联系 | LORA"),
    description: text(
      "Contact LORA and schedule a project brief.",
      "Связаться с LORA и назначить бриф по проекту.",
      "Contacta con LORA y agenda un briefing.",
      "联系 LORA 并安排项目沟通。",
    ),
    h1: text("Contacts", "Контакты", "Contacto", "联系"),
    summary: text(
      "Email, brief form and project intake information.",
      "Email, форма брифа и данные для первичного обращения.",
      "Email y formulario de briefing.",
      "邮箱与项目表单。",
    ),
    changeFrequency: "monthly",
    priority: 0.7,
  },
  {
    kind: "simple",
    path: "/audit",
    slug: "audit",
    title: text("Audit and brief | LORA", "Аудит и бриф | LORA", "Auditoria y brief | LORA", "审计与 brief | LORA"),
    description: text(
      "Request an audit and project brief before starting a website, CRM or automation project.",
      "Запросить аудит и бриф перед запуском сайта, CRM или автоматизации.",
      "Solicita auditoria y brief antes de iniciar sitio, CRM o automatizacion.",
      "在启动网站、CRM 或自动化项目前申请审计与 brief。",
    ),
    h1: text("Audit and brief", "Аудит и бриф", "Auditoria y brief", "审计与 brief"),
    summary: text(
      "A focused entry point for reading context, finding weak points and defining project scope.",
      "Точка входа для чтения контекста, поиска слабых мест и определения состава проекта.",
      "Punto de entrada para leer contexto y definir alcance.",
      "用于阅读背景、发现薄弱点并定义项目范围的入口。",
    ),
    changeFrequency: "monthly",
    priority: 0.8,
  },
  {
    kind: "simple",
    path: "/privacy",
    slug: "privacy",
    title: text(
      "Privacy policy | LORA",
      "Политика конфиденциальности | LORA",
      "Politica de privacidad | LORA",
      "隐私政策 | LORA",
    ),
    description: text(
      "How LORA handles request data, briefs, project communication and analytics events.",
      "Как LORA обрабатывает данные заявок, брифов, проектной коммуникации и аналитические события.",
      "Como LORA procesa solicitudes, briefs y eventos analiticos.",
      "LORA 如何处理请求、项目沟通和分析事件。",
    ),
    h1: text("Privacy policy", "Политика конфиденциальности", "Politica de privacidad", "隐私政策"),
    summary: text(
      "Clear rules for contact data, project context, retention, deletion requests and service providers.",
      "Понятные правила для контактных данных, проектного контекста, сроков хранения, удаления и технических сервисов.",
      "Reglas claras para datos de contacto y contexto de proyecto.",
      "联系数据与项目上下文的清晰规则。",
    ),
    changeFrequency: "yearly",
    priority: 0.35,
  },
  {
    kind: "simple",
    path: "/cookies",
    slug: "cookies",
    title: text("Cookie notice | LORA", "Cookie notice | LORA", "Aviso de cookies | LORA", "Cookie 说明 | LORA"),
    description: text(
      "Cookie, browser storage, analytics and advertising measurement notice for the LORA site.",
      "Уведомление о cookie, хранении в браузере, аналитике и рекламных измерениях на сайте LORA.",
      "Aviso de cookies, almacenamiento, analitica y publicidad.",
      "Cookie、浏览器存储、分析和广告衡量说明。",
    ),
    h1: text("Cookie notice", "Cookie и аналитика", "Aviso de cookies", "Cookie 说明"),
    summary: text(
      "What the site may store, which analytics events are prepared and how users can control browser storage.",
      "Что сайт может хранить, какие события аналитики подготовлены и как пользователь может управлять хранением в браузере.",
      "Que puede almacenar el sitio y como controlar cookies.",
      "网站可能存储什么以及如何控制浏览器存储。",
    ),
    changeFrequency: "yearly",
    priority: 0.3,
  },
  {
    kind: "simple",
    path: "/terms",
    slug: "terms",
    title: text("Terms of use | LORA", "Правила пользования | LORA", "Terminos de uso | LORA", "使用条款 | LORA"),
    description: text(
      "Rules for using the LORA website, forms, materials and contact channels before a separate agreement.",
      "Правила пользования сайтом LORA, формами, материалами и контактными каналами до отдельного договора.",
      "Reglas para usar el sitio, formularios y materiales de LORA.",
      "LORA 网站、表单和材料使用规则。",
    ),
    h1: text("Terms of use", "Правила пользования", "Terminos de uso", "使用条款"),
    summary: text(
      "How to use the site, what is prohibited, how requests work and why site content is not a public offer.",
      "Как пользоваться сайтом, что запрещено, как работают заявки и почему материалы сайта не являются публичной офертой.",
      "Como usar el sitio y enviar solicitudes.",
      "如何使用网站以及请求如何运作。",
    ),
    changeFrequency: "yearly",
    priority: 0.3,
  },
  {
    kind: "simple",
    path: "/thank-you",
    slug: "thank-you",
    title: text("Thank you | LORA", "Спасибо | LORA", "Gracias | LORA", "谢谢 | LORA"),
    description: text(
      "Confirmation page after sending a request to LORA.",
      "Страница подтверждения после отправки заявки в LORA.",
      "Pagina de confirmacion despues de enviar una solicitud.",
      "提交请求后的确认页面。",
    ),
    h1: text("Thank you", "Спасибо", "Gracias", "谢谢"),
    summary: text(
      "We received the request and will review the project context.",
      "Заявка получена, команда изучит контекст проекта.",
      "Recibimos la solicitud.",
      "我们已收到请求。",
    ),
    changeFrequency: "yearly",
    priority: 0.2,
    noindex: true,
  },
];
